package com.caas.app.domain.usecase

import com.caas.app.core.result.Result
import com.caas.app.data.model.PurchaseOrder
import com.caas.app.data.model.PurchaseOrderItem
import com.caas.app.data.model.PurchaseOrderStatus
import com.caas.app.domain.repository.PurchaseOrderRepository
import com.caas.app.domain.repository.ProviderRepository
import com.caas.app.domain.repository.StockRepository

/**
 * RF-40: Genera automáticamente órdenes de compra por proveedor
 * para productos con stock por debajo del mínimo.
 */
class AutoGeneratePurchaseOrderUseCase(
    private val stockRepository: StockRepository,
    private val providerRepository: ProviderRepository,
    private val purchaseOrderRepository: PurchaseOrderRepository
) {

    suspend operator fun invoke(
        businessId: String,
        branchId: String
    ): Result<List<PurchaseOrder>> {
        if (businessId.isBlank()) return Result.Error("El ID del negocio es requerido")
        if (branchId.isBlank()) return Result.Error("El ID de la sucursal es requerido")

        val stockResult = stockRepository.getStockByBranch(businessId, branchId)
        if (stockResult is Result.Error) return stockResult

        val allStock = (stockResult as Result.Success).data
        val lowStockItems = allStock.filter { it.quantity < it.minStock }

        if (lowStockItems.isEmpty()) {
            return Result.Success(emptyList())
        }

        // Agrupa productos por proveedor (proveedorId → lista de items)
        val ordersByProvider = mutableMapOf<String, MutableList<Pair<String, PurchaseOrderItem>>>()

        for (stockItem in lowStockItems) {
            val providersResult = providerRepository.getProvidersByProduct(businessId, stockItem.productId)
            if (providersResult is Result.Error) continue

            val providers = (providersResult as Result.Success).data
            val provider = providers.firstOrNull() ?: continue

            val neededQty = stockItem.minStock - stockItem.quantity
            val orderItem = PurchaseOrderItem(
                productId = stockItem.productId,
                productName = stockItem.productName,
                quantity = neededQty,
                unitCost = 0.0
            )

            ordersByProvider
                .getOrPut(provider.id) { mutableListOf() }
                .add(Pair(provider.name, orderItem))
        }

        val createdOrders = mutableListOf<PurchaseOrder>()
        val now = System.currentTimeMillis()

        for ((providerId, providerItems) in ordersByProvider) {
            val providerName = providerItems.first().first
            val items = providerItems.map { it.second }

            val orderId = "${businessId}_${System.nanoTime()}"
            val order = PurchaseOrder(
                id = orderId,
                businessId = businessId,
                branchId = branchId,
                providerId = providerId,
                providerName = providerName,
                status = PurchaseOrderStatus.PENDING,
                items = items,
                isAutoGenerated = true,
                notes = "",
                createdBy = "",
                createdAt = now,
                updatedAt = now
            )

            val createResult = purchaseOrderRepository.createPurchaseOrder(order)
            if (createResult is Result.Success) {
                createdOrders.add(order)
            }
        }

        return Result.Success(createdOrders)
    }
}
