package com.caas.app.domain.usecase

import com.caas.app.core.result.Result
import com.caas.app.data.model.PurchaseOrder
import com.caas.app.data.model.PurchaseOrderItem
import com.caas.app.data.model.PurchaseOrderStatus
import com.caas.app.domain.repository.PurchaseOrderRepository

/**
 * RF-41: Crea una nueva orden de compra manual con validaciones.
 */
class CreatePurchaseOrderUseCase(
    private val purchaseOrderRepository: PurchaseOrderRepository
) {

    suspend operator fun invoke(
        businessId: String,
        branchId: String,
        providerId: String,
        providerName: String,
        items: List<PurchaseOrderItem>,
        notes: String = "",
        createdBy: String = ""
    ): Result<PurchaseOrder> {
        if (businessId.isBlank()) return Result.Error("El ID del negocio es requerido")
        if (branchId.isBlank()) return Result.Error("El ID de la sucursal es requerido")
        if (providerId.isBlank()) return Result.Error("El proveedor es requerido")
        if (items.isEmpty()) return Result.Error("La orden debe tener al menos un producto")
        if (items.any { it.quantity <= 0 }) return Result.Error("Todos los productos deben tener cantidad mayor a 0")

        val now = System.currentTimeMillis()
        val orderId = "${businessId}_${System.nanoTime()}"

        val order = PurchaseOrder(
            id = orderId,
            businessId = businessId,
            branchId = branchId,
            providerId = providerId,
            providerName = providerName,
            status = PurchaseOrderStatus.PENDING,
            items = items,
            isAutoGenerated = false,
            notes = notes,
            createdBy = createdBy,
            createdAt = now,
            updatedAt = now
        )

        return purchaseOrderRepository.createPurchaseOrder(order)
    }
}
