package com.caas.app.data.model

import com.google.firebase.firestore.PropertyName

data class PurchaseOrder(
    val id: String = "",
    val businessId: String = "",
    val branchId: String = "",
    val providerId: String = "",
    val providerName: String = "",
    val status: PurchaseOrderStatus = PurchaseOrderStatus.PENDING,
    val items: List<PurchaseOrderItem> = emptyList(),
    @get:PropertyName("isAutoGenerated") @set:PropertyName("isAutoGenerated") var isAutoGenerated: Boolean = false,
    val notes: String = "",
    val createdBy: String = "",
    val createdAt: Long = 0L,
    val updatedAt: Long = 0L
)

data class PurchaseOrderItem(
    val productId: String = "",
    val productName: String = "",
    val quantity: Int = 0,
    val unitCost: Double = 0.0
)

enum class PurchaseOrderStatus {
    PENDING,    // Pendiente
    SENT,       // Enviada
    RECEIVED,   // Recibida
    CANCELLED   // Cancelada
}
