package com.caas.app.ui.purchase.adapter

import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.recyclerview.widget.DiffUtil
import androidx.recyclerview.widget.ListAdapter
import androidx.recyclerview.widget.RecyclerView
import com.caas.app.R
import com.caas.app.data.model.PurchaseOrder
import com.caas.app.data.model.PurchaseOrderStatus
import com.caas.app.databinding.ItemPurchaseOrderBinding
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class PurchaseOrderAdapter(
    private val onClick: (PurchaseOrder) -> Unit
) : ListAdapter<PurchaseOrder, PurchaseOrderAdapter.ViewHolder>(DiffCallback) {

    inner class ViewHolder(private val binding: ItemPurchaseOrderBinding) :
        RecyclerView.ViewHolder(binding.root) {

        fun bind(order: PurchaseOrder) {
            binding.tvProviderName.text = order.providerName
            binding.tvItemCount.text = "${order.items.size} producto(s)"

            val sdf = SimpleDateFormat("dd/MM/yyyy", Locale.getDefault())
            binding.tvDate.text = sdf.format(Date(order.createdAt))

            val total = order.items.sumOf { it.quantity * it.unitCost }
            binding.tvTotal.text = if (total > 0) "$ %.2f".format(total) else "${order.items.sumOf { it.quantity }} unid."

            binding.ivAutoGenerated.visibility =
                if (order.isAutoGenerated) View.VISIBLE else View.GONE

            val (statusText, statusColor) = when (order.status) {
                PurchaseOrderStatus.PENDING -> "Pendiente" to R.color.yellow
                PurchaseOrderStatus.SENT -> "Enviada" to R.color.blue
                PurchaseOrderStatus.RECEIVED -> "Recibida" to R.color.green
                PurchaseOrderStatus.CANCELLED -> "Cancelada" to R.color.red
            }
            binding.chipStatus.text = statusText
            binding.chipStatus.setChipBackgroundColorResource(statusColor)

            binding.root.setOnClickListener { onClick(order) }
        }
    }

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
        val binding = ItemPurchaseOrderBinding.inflate(
            LayoutInflater.from(parent.context), parent, false
        )
        return ViewHolder(binding)
    }

    override fun onBindViewHolder(holder: ViewHolder, position: Int) {
        holder.bind(getItem(position))
    }

    companion object DiffCallback : DiffUtil.ItemCallback<PurchaseOrder>() {
        override fun areItemsTheSame(oldItem: PurchaseOrder, newItem: PurchaseOrder) =
            oldItem.id == newItem.id

        override fun areContentsTheSame(oldItem: PurchaseOrder, newItem: PurchaseOrder) =
            oldItem == newItem
    }
}
